name: flutter_url_image_load_fail
description: Flutter - Load a Image from an URL and define widgets to loading and failed states
version: 1.0.0
homepage: https://github.com/WiseTap/flutter_url_image_load_fail/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
    
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
